site_name: Valerian Borisovich
edit_uri: tree/master/
docs_dir: pages

theme:
  name: material
  #custom_dir: docs/overrides
  logo: docs/assets/obsidian.png
  #logo: assets/logo.png
  #favicon: assets/logo.png
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: blue-grey
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      #primary: deep purple
      #accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant

nav:
  - Overview: index.md
  - General Concepts: general.md
  - Settings: settings.md
  - Controls: controls.md
  - FileClasses: fileclasses.md
  - API: api.md

repo_url: https://github.com/valerian-borisovich/valerian-borisovich.github.io

#extra_javascript:
#  - extras/matomo.js

#extra_css:
#  - extras/styles.css
  
markdown_extensions:
  - toc:
     permalink: True
  - fenced_code
  - tables
  - nl2br
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.tabbed

plugins:
  - search
  - roamlinks
  - tags:
      tags_file: tagindex.md
