site_name: Valerian Borisovich Vault
repo_url: https://github.com/valerian-borisovich/valerian-borisovich.github.io
edit_uri: tree/main/.publish/docs/
#edit_uri: tree/master/
# docs_dir: pages

theme:
  name: material
  custom_dir: docs/overrides
  palette:
    scheme: slate
    primary: deep purple
    accent: deep purple
  logo: assets/logo.png
  favicon: assets/logo.png
  features:
    - navigation.instant

markdown_extensions:
  - toc:
      permalink: True
  - fenced_code
  - tables
  - admonition
  - nl2br

extra_javascript:
  - extras/matomo.js
  - dataview_views/tagcloud/view.js
  - dataview_views/imagegrid/view.js
  - dataview_views/usedInAUseCase/view.js
  - dataview_views/year_overview/view.js

extra_css:
  - extras/styles.css
  - dataview_views/tagcloud/view.css
  - dataview_views/imagegrid/view.css
  - dataview_views/year_overview/view.css

plugins:
  - search
  - roamlinks
  - tags:
      tags_file: tagindex.md

nav:
  - Home: index.md
  - About: about.md
  - Overview: Overview.md
  - DataviewQueries: DataviewQueries.md
  - DVJSfunction: DVJSfunction.md
